//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterRising.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WaterRising.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {tree, sapling, seedling, timber, wood, hardwood, softwood}
        ///{mountain, hill, bluff, cliff, peak, ridge, volcano, alp, butte, crag, mound, precipice, dune, hillside, hilltop, slope, hillock, incline, knoll, mesa, mount, summit}
        ///{shrub, fern, hedge, plant, bramble, berry, brush, thicket, shrubbery}
        ///{water, aqua, tears, h2o}.
        /// </summary>
        internal static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {climb, scale, ascend, clamber, go up, mount, rise, top}
        ///{mine, dig, quarry, excavate, bore, burrow, drill, gouge, shovel, sift, uncover, unearth, channel, tunnel, undermine}
        ///{gather, harvest, collect, pick, accumulate, amass, hoard, stockpile, bag, pluck, cut, chop, cleave, hack, mince}
        ///{eat, bite, masticate, chew, devour, dine, feed, ingest, inhale, nibble, swallow, digest, gorge, graze, lunch, munch, snack, sup, wolf down, wolf, chow down, feast, feast upon, gobble up, partake in}
        ///{attack, damage, ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
